"""Second Migration for changes in user class

Revision ID: 126ea925daa9
Revises: 43ba7cc675b7
Create Date: 2018-06-24 23:43:54.797552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126ea925daa9'
down_revision = '43ba7cc675b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
