"""changes to pitch class

Revision ID: 1eb964d9a352
Revises: ae07c174daea
Create Date: 2018-06-26 08:42:49.423848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb964d9a352'
down_revision = 'ae07c174daea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['author'], ['id'])
    op.drop_column('pitches', 'pitch_desc')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'pitch_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'author')
    # ### end Alembic commands ###
