"""changes to pitch class

Revision ID: 2c6a8a3228be
Revises: 1eb964d9a352
Create Date: 2018-06-26 08:55:02.095198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6a8a3228be'
down_revision = '1eb964d9a352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_title', sa.String(), nullable=True))
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch_title')
    # ### end Alembic commands ###
