"""changes in the like class

Revision ID: 7893382f2a05
Revises: 659aba22f24b
Create Date: 2018-06-29 10:41:52.942940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7893382f2a05'
down_revision = '659aba22f24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'like')
    # ### end Alembic commands ###
